### ISSUE TITLE
roster disappears

### ISSUE THREAD

**Issue by tenbergen** [tenbergen/CSC480-22S#254]
After a while, the roster disappears and isn't shown in the GUI. hoping that running sh build-app.sh will fix it.

**Comment by tenbergen** [comment]
rebuilding the app did not help. uploading a new CSV to the exiting course also did not help, it would error out and say "error uploading CSV". I had to create a new course.

**Comment by tenbergen** [comment]
I can upload a new CSV in the new course, but the roster remains empty. adding a student manually (after uploading a CSV) also resulted in an "error adding student."

**Comment by tenbergen** [comment]
creating a new course, uploading CSV and manually adding students errors out.

**Comment by lunarmint** [comment]
Related to issue #255, this might be because the web server was down temporarily on top of multiple docker containers were being ran for the same microservice. It seems fine for now, but I will keep this opened and look further into it to confirm the root cause.

**Comment by lunarmint** [comment]
I found where the issue is -

1. The algorithm that checks the `professor-list.txt` is faulty. If a student in course A also somehow happens to be a professor at the same time, on login, they're going to be removed from the student database (and moved into the professor database), but not from the student list in that course per se.

2. Front end should have thrown an exception and move on and render the rest of the list instead of just straight up breaking when it cannot retrieve one of the students from the student list of the course from the student database.

**Comment by logann131** [comment]
Seems like the final development phase of the technical teams last semester might have made many conflicts in the database. Just got the database purged and now things are working fine now.
