### ISSUE TITLE
CPR tool showing extra courses

### ISSUE THREAD

**Issue by MatthewDBrown50** [tenbergen/CSC480-22S#267]
In addition to my registered course, CSC 385, the CPR tool shows me MCS 101 (Midlife Crisis) and CSC 495 (Software Engineering). I am not registered for these courses. It also shows me CSC385-800-800 ("roster test"), which I assume was only meant to be viewed internally.

**Comment by logann131** [comment]
Hello Matthew,
thanks for opening the issue. 
You were right it looks like @lunarmint was working to fix the issue #253 and he used CSC 385's roster list as an argument that's why you see the extra courses. He will make changes on that so it will show the only courses that you register for.

Cheers,
Logan

**Comment by lunarmint** [comment]
Hi, thank you for the issue. In fact, it was a course I created for testing purpose and added some of you to test things out. I'll remove it soon to prevent further confusions. Sorry and thank you for letting me know.
