### ISSUE TITLE
Unable to create a proper team

### ISSUE THREAD

**Issue by MatthewDBrown50** [tenbergen/CSC480-22S#268]
Upon viewing courses, the only option available to me is a "Create New Team" button. Clicking the button prompts me to create a team name. After providing a team name, it creates the team and brings me to a screen with 3 tabs: To Do, Submitted, and My Team.

My Team tab shows the Team (the name I submitted) and Members (just me). There is no option to add additional members.

The 'To Do' and 'Submitted' tabs have nothing to show.

**Comment by logann131** [comment]
Hello Matthew,
Thanks for opening the issue. 
By default, when you create a team, the team will have the team size = 1, that's why you can't invite any other student. In order to do that, you will have to inform the instructor (BT in this case) to modify the team size so you can add more teammates.

The `To do`  page is to show the assignments `IF` there is any. If the professor didn't make any assignment, it will show `nothing to show` message.

Same go for the `Submitted`. This page shows your submissions, `IF` you didn't make any submission, it will then show `nothing to show` message again.

**Comment by tenbergen** [comment]
@logann131 team size is set to "2" in the course in question. I manually added a partner for matt, which worked.

**Comment by MatthewDBrown50** [comment]
Understood. Thanks Logan.

Sent from my iPhone

On Sep 1, 2022, at 12:25 PM, Bastian Tenbergen ***@***.***> wrote:

﻿

@logann131<https://github.com/logann131> team size is set to "2" in the course in question. I manually added a partner for matt, which worked.

**Comment by logann131** [comment]
Awesome thank you @tenbergen!
Please close the issue if we believe the issue has been solved! (I don't have the power 😓)
